"""Deterministic source policy shared by writing, audit, and repair.

The ledger is built from the locked source pack, never generated by another
model. It gives every later model the same claim boundary for one run.
"""
from __future__ import annotations

import json
from typing import Any


POLICY_VERSION = 2

# These are common named frameworks that must not leak from a prior run. A term
# is allowed only when this run's source evidence explicitly contains it.
KNOWN_NAMED_FRAMEWORKS = (
    "課題の分離",
    "アドラー心理学",
    "愛着理論",
    "認知行動療法",
    "スキーマ療法",
    "ポリヴェーガル理論",
    "トラウマ反応",
)

FRAMEWORK_SOURCE_ALIASES = {
    "アドラー心理学": ("課題の分離",),
}

# A short-term relief -> repeated behavior loop is a distinct causal claim.
# It must be explicitly present in the locked source evidence, not inferred
# merely because a topic has a cost or a paradox.
REINFORCEMENT_SUPPORT_MARKERS = (
    "negative reinforcement", "reinforcement loop", "avoidance reinforcement",
    "avoidance maintains", "short-term relief", "short term relief",
    "負の強化", "強化される", "強化する", "回避が維持", "回避を維持",
    "一時的な安心", "一時的に不安を下げ", "短期的な安心",
    "củng cố hành vi", "duy trì hành vi", "giảm khó chịu tạm thời",
)


def _source_evidence(source_pack: dict[str, Any]) -> str:
    verified = source_pack.get("verified_sources") or []
    supports = [
        "%s %s" % (item.get("title", ""), item.get("supports", ""))
        for item in verified
        if isinstance(item, dict)
    ]
    return " ".join(
        [
            str(source_pack.get("source_concept", "")),
            *[str(item) for item in source_pack.get("allowed_paraphrases", [])],
            *supports,
        ]
    )


def _verified_source_evidence(source_pack: dict[str, Any]) -> str:
    """Return only claims explicitly supplied by verified source entries.

    `editorial_application` is an editorial lens and must never unlock a new
    causal capability. Keeping this evidence boundary separate prevents a model
    from granting itself reinforcement claims through metadata.
    """
    verified = source_pack.get("verified_sources") or []
    return " ".join(
        "%s %s" % (item.get("title", ""), item.get("supports", ""))
        for item in verified
        if isinstance(item, dict)
    )


def source_supports_reinforcement_loop(source_pack: dict[str, Any]) -> bool:
    """Whether this source pack explicitly supports a relief-maintenance loop."""
    evidence = _verified_source_evidence(source_pack).lower()
    return any(marker.lower() in evidence for marker in REINFORCEMENT_SUPPORT_MARKERS)


def build_claim_ledger(source_pack: dict[str, Any]) -> dict[str, Any]:
    evidence = _source_evidence(source_pack)
    claims: list[dict[str, str]] = []

    concept = str(source_pack.get("source_concept", "")).strip()
    if concept:
        claims.append({
            "id": "source_concept",
            "claim": concept,
            "support": "source_pack.source_concept",
            "usage": "May name or explain this concept within the verified support.",
        })
    for index, statement in enumerate(source_pack.get("allowed_paraphrases") or [], start=1):
        text = str(statement).strip()
        if text:
            claims.append({
                "id": "paraphrase_%02d" % index,
                "claim": text,
                "support": "source_pack.allowed_paraphrases",
                "usage": "May be paraphrased without increasing causal certainty.",
            })
    for index, source in enumerate(source_pack.get("verified_sources") or [], start=1):
        if not isinstance(source, dict):
            continue
        support = str(source.get("supports", "")).strip()
        if support:
            claims.append({
                "id": "verified_source_%02d" % index,
                "claim": support,
                "support": str(source.get("url", "")),
                "usage": "Use only at the level expressed in this support statement.",
            })

    forbidden_terms = {
        str(term).strip()
        for term in source_pack.get("forbidden_attributions") or []
        if str(term).strip()
    }
    for term in KNOWN_NAMED_FRAMEWORKS:
        aliases = FRAMEWORK_SOURCE_ALIASES.get(term, ())
        if term not in evidence and not any(alias in evidence for alias in aliases):
            forbidden_terms.add(term)

    return {
        "version": POLICY_VERSION,
        "authority": "locked_source_pack",
        "allowed_claims": claims,
        "editorial_application": {
            "text": str(source_pack.get("editorial_application", "")).strip(),
            "rule": "May be used as a bounded interpretive lens, never as a separately proven causal mechanism.",
        },
        "forbidden_terms": sorted(forbidden_terms),
        "forbidden_claim_categories": [
            "named framework or author absent from this run's sources",
            "causal mechanism beyond the stated support",
            "diagnosis, childhood cause, trauma cause, or neuroscience claim without support",
        ],
        "capabilities": {
            "reinforcement_loop": source_supports_reinforcement_loop(source_pack),
        },
    }


def validate_claim_ledger(value: dict[str, Any]) -> None:
    required = ("version", "authority", "allowed_claims", "editorial_application", "forbidden_terms", "forbidden_claim_categories")
    missing = [key for key in required if key not in value]
    if missing:
        raise ValueError("claim_ledger thiếu field: %s" % ", ".join(missing))
    if value["version"] != POLICY_VERSION or value["authority"] != "locked_source_pack":
        raise ValueError("claim_ledger không đúng policy version/authority.")
    if not isinstance(value["allowed_claims"], list) or not value["allowed_claims"]:
        raise ValueError("claim_ledger phải có ít nhất một allowed claim.")
    if not isinstance(value["forbidden_terms"], list):
        raise ValueError("claim_ledger.forbidden_terms phải là danh sách.")


def attach_claim_ledger(source_pack: dict[str, Any], ledger: dict[str, Any]) -> dict[str, Any]:
    value = json.loads(json.dumps(source_pack, ensure_ascii=False))
    value["claim_ledger"] = ledger
    return value


def policy_violations(text: str, ledger: dict[str, Any]) -> list[str]:
    content = str(text or "")
    return [term for term in ledger.get("forbidden_terms", []) if term and term in content]
